# Various functions in NumPy

In [2]:
import numpy as np

l = range(1000)
%timeit [i**2 for i in l]

352 μs ± 18.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
n = np.arange(1000)
%timeit [j**2 for j in n]

157 µs ± 27.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#L1 = range(1000)

In [ ]:
a = np.array([0,1,2,3])
print(a.ndim)
print(a.shape)

1
(4,)


In [ ]:
a = np.array([(0,1,2,3),(7,8,9,4)])
print(a.ndim)
print(a.shape)

2
(2, 4)


In [ ]:
a = np.array([(0,1,2,3),(7,8,9,4),(8,7,6,5)])
print(a.ndim)
print(a.shape)

2
(3, 4)


In [ ]:
a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
a= np.array([1,2,3,4])
a[1:]

array([2, 3, 4])

In [3]:
import numpy.ma as ma
x = np.array([1, 2, 3, -1, 5])

In [8]:
mx = ma.masked_array(x, mask=[0, 0, 0, 1, 0])
mx.mean()


np.float64(2.75)